name: GitHub Events Analytics CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -r data-collector/requirements.txt
        pip install -r spark-jobs/requirements.txt
        
    - name: Run tests
      run: |
        pytest --cov=data-collector --cov=spark-jobs
        
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
        
    - name: Lint with flake8
      run: |
        flake8 data-collector spark-jobs --count --select=E9,F63,F7,F82 --show-source --statistics
        
    - name: Check formatting with black
      run: |
        black --check data-collector spark-jobs
        
    - name: Check imports with isort
      run: |
        isort --check-only --profile black data-collector spark-jobs
        
  docker:
    runs-on: ubuntu-latest
    needs: [test, lint]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push data collector
      uses: docker/build-push-action@v4
      with:
        context: ./data-collector
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/github-events-collector:latest
        
    - name: Build and push spark jobs
      uses: docker/build-push-action@v4
      with:
        context: ./spark-jobs
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/github-events-processor:latest 